-- CREATE A VISUALIZATION THAT PROVIDE A BREAKDOWN BETWEEN THE MAL AND FEMALE EMPLOYEES WORKING IN THE COMPANY EACH YEAR STARTING FROM 1990.

SELECT 
	YEAR(D.from_date)AS YEAR,
    E.gender,
    COUNT(E.EMP_NO)
FROM 
	T_EMPLOYEES e
JOIN 
	t_dept_emp D
ON 
	E.EMP_NO = D.EMP_NO
GROUP BY 
	YEAR;
    
    
SELECT 
	EMP_NO,
	FROM_DATE,
	TO_DATE
FROM 
	t_dept_emp;
    
SELECT DISTINCT 
	EMP_NO,
	FROM_DATE,
	TO_DATE
FROM 
	T_DEPT_EMP;
    
# PROBLEM 1:SOLUTION IN SQL

SELECT 
	YEAR(D.FROM_DATE) AS CALENDAR_YEAR,
	E.GENDER,
    COUNT(E.EMP_NO) AS NUM_OF_EMPLOYEES
FROM 
	T_EMPLOYEES e
JOIN 
	t_dept_emp D
ON 
	E.EMP_NO = D.EMP_NO
GROUP BY 
	CALENDAR_YEAR,
    E.GENDER
HAVING 
	CALENDAR_YEAR>=1990;