select 
	EMP_NO,
    FIRST_NAME,
    LAST_NAME,
    CASE 
		WHEN GENDER = 'M' THEN 'MALE'
        ELSE 'FEMALE'
	END AS GENDER
FROM 
	employees;
   

select 
	EMP_NO,
    FIRST_NAME,
    LAST_NAME,
    CASE GENDER
		WHEN 'M' THEN 'MALE'
        ELSE 'FEMALE'
	END AS GENDER
FROM 
	employees;
    
    
select 
	E.EMP_NO,
    E.FIRST_NAME,
    E.LAST_NAME,
    CASE 
		WHEN DM.EMP_NO IS NOT NULL THEN 'MANAGER' 
		ELSE 'EMPLOYEE'
	END AS IS_MANAGER
FROM 
	employees E
    LEFT JOIN 
		DEPT_MANAGER DM 
	ON 
		DM.EMP_NO = E.EMP_NO
WHERE
	E.EMP_NO > 109990;
    
    
-- EXERCISE :
select 
	E.EMP_NO,
    E.FIRST_NAME,
    E.LAST_NAME,
    CASE DM.EMP_NO
		WHEN NOT NULL  THEN 'MANAGER' 
		ELSE 'EMPLOYEE'
	END AS IS_MANAGER
FROM 
	employees E
    LEFT JOIN 
		DEPT_MANAGER DM 
	ON 
		DM.EMP_NO = E.EMP_NO
WHERE
	E.EMP_NO > 109990;   
    
    
SELECT 
	EMP_NO,
    FIRST_NAME,
    LAST_NAME,
    IF(GENDER = 'M' , 'MALE' , 'FEMALE')
		AS GENDER
FROM employees;


SELECT 
	DM.EMP_NO,
	E.FIRST_NAME,
    E.LAST_NAME,
    MAX(S.SALARY) - MIN(S.SALARY) AS SALARY_DIFFERENCE,
    CASE 
		WHEN MAX(S.SALARY) - MIN(S.SALARY) >30000 THEN 'SALARY WAS RAISED  BY MORE THAN THAN $30000'
        WHEN MAX(S.SALARY) - MIN(S.SALARY) BETWEEN 20000 AND 30000 THEN 'SALARY WAS RAISED  BY MORE THAN THAN $20000 BUT LESS THAN $30000'
        ELSE 'SALARY WAS RAISED BY LESS THAN $20000'
	END AS SALARY_INCREASE
FROM
	DEPT_MANAGER DM
	JOIN 
		employees E
	ON
		E.EMP_NO = DM.EMP_NO
	JOIN
		SALARIES S 
	ON	
		S.EMP_NO=DM.EMP_NO
GROUP BY S.EMP_NO;
	