-- SELECT *
-- FROM employees
-- WHERE FIRST_NAME <> 'MARK';

-- SELECT *
-- FROM employees
-- WHERE FIRST_NAME = 'MARK';

-- SELECT *
-- FROM employees
-- WHERE FIRST_NAME != 'MARK';


/*
SELECT FIRST_NAME FROM EMPLOYEES WHERE HIRE_DATE IS GREATER THAN OR EQUALS TO 2000-01-01
*/
-- SELECT *
-- FROM employees
-- WHERE HIRE_DATE >= '2000-01-01';


/*
SELECT FIRST_NAME FROM EMPLOYEES WHERE HIRE_DATE IS LESS THAN OR EQUALS TO 1985-02-01
*/
SELECT *
FROM employees
WHERE HIRE_DATE <= '1985-02-01';