-- SELECT FIRST_NAME
-- FROM EMPLOYEES;

-- SELECT first_name
-- FROM employees
-- GROUP BY FIRST_NAME;

-- select DISTINCT FIRST_NAME
-- FROM EMPLOYEES;
 /*
 SELECTING TOTAL NUMBER OF FIRST_NAME OCCCURED
 */
SELECT FIRST_NAME , COUNT(FIRST_NAME)
FROM EMPLOYEES
GROUP BY FIRST_NAME
ORDER BY FIRST_NAME;
