/*
EXTRACT ALL FIRSTNAMES THAT APPEAR MORE THAN 250 TIMES IN THE "EMPLOYEES" TABLES.
*/
SELECT FIRST_NAME , COUNT(FIRST_NAME) AS NAMES_COUNT
FROM EMPLOYEES
GROUP BY FIRST_NAME
HAVING COUNT(FIRST_NAME) >250
ORDER BY FIRST_NAME;