DROP FUNCTION IF EXISTS F_EMP_AVG_SALARY;

DELIMITER $$
CREATE FUNCTION F_EMP_AVG_SALARY(P_EMP_NO INTEGER) RETURNS decimal(10,2)
DETERMINISTIC NO SQL READS SQL DATA
BEGIN
DECLARE V_AVG_SALARY DECIMAL(10,2);

BEGIN
	DECLARE V_AVG_SALARY_2 DECIMAL(10,2);
END ; 

SELECT
	AVG(S.SALARY)
INTO
	V_AVG_SALARY_2
FROM 
	EMPLOYEES E
JOIN
	SALARIES S
ON 
	S.EMP_NO = E.EMPP_NO
WHERE 
	E.EMP_NO = P_EMP_NO;
RETURN V_AVG_SALARY;
END $$

DELIMITER ;

-- SELECT V_AVG_SLALRY;