SELECT *
FROM EMP_MANAGER
ORDER BY EMP_MANAGER.EMP_NO;

# FROM THE EMP_MANAGER TABLE , EXTRACT THE RECORD DATA ONLY OF THOSE EMPLOYEES WHO ARE MANAGERS AS WELL.
SELECT DISTINCT e1.*
FROM EMP_MANAGER E1
JOIN EMP_MANAGER E2 
ON E1.EMP_NO = E2.MANAGER_NO;

SELECT e1.*
FROM EMP_MANAGER E1
JOIN EMP_MANAGER E2 
ON E1.EMP_NO = E2.MANAGER_NO
WHERE E2.EMP_NO IN (
	SELECT MANAGER_NO
    FROM emp_manager
);

SELECT MANAGER_NO
    FROM emp_manager;