USE EMPLOYEES;
DROP PROCEDURE IF EXISTS EMP_AVG_SALARY_OUT;
/*
	SELECT INTO STRUCTURE
*/
DELIMITER $$
CREATE PROCEDURE EMP_AVG_SALARY_OUT(IN P_EMP_NO INTEGER , OUT P_AVG_SALARY DECIMAL(10,2))
BEGIN
	SELECT 
        AVG(S.SALARY)
	INTO 
		P_AVG_SALARY
	FROM 
		EMPLOYEES E
		JOIN
			SALARIES S
		ON 
			E.EMP_NO = S.EMP_NO
	WHERE 
		E.EMP_NO = P_EMP_NO;
END $$

DELIMITER ;

