USE EMPLOYEES;
DROP PROCEDURE IF EXISTS EMP_AVG_SALARY;

DELIMITER $$
USE EMPLOYEES $$
CREATE PROCEDURE EMP_AVG_SALARY(IN P_EMP_NO INTEGER)
BEGIN
	SELECT 
		E.FIRST_NAME,
        E.LAST_NAME,
        AVG(S.SALARY)
	FROM 
		EMPLOYEES E
    JOIN
		SALARIES S
	ON 
		E.EMP_NO = S.EMP_NO
	WHERE 
		E.EMP_NO = P_EMP_NO;
END $$

DELIMITER ;

CALL EMP_AVG_SALARY(11300);