SELECT * FROM EMPLOYEES
WHERE EMP_NO = 999901;

UPDATE EMPLOYEES
SET FIRST_NAME = 'Stella',
LAST_NAME = 'Parkinson',
BIRTH_DATE='1990-12-31',
GENDER = 'F'
WHERE EMP_NO = 999901;

SELECT * FROM EMPLOYEES
ORDER BY EMP_NO DESC
LIMIT 10;