SELECT 
	*
FROM 
	DEPT_EMP;

SELECT 
	EMP_NO,
	FROM_DATE,
    TO_DATE,
    COUNT(EMP_NO) AS NUM
FROM dept_emp
GROUP BY EMP_NO
HAVING NUM > 1;

SELECT 
	EMP_NO,
	FROM_DATE,
    TO_DATE,
    COUNT(EMP_NO) AS NUM
FROM dept_emp
GROUP BY EMP_NO
HAVING NUM = 1;

CREATE OR REPLACE VIEW V_DEPT_EMP_LATEST_DATE AS
SELECT 
	EMP_NO ,
    MAX(FROM_DATE) AS FROM_DATE ,
    MAX(TO_DATE) AS TO_DATE
FROM dept_emp
GROUP BY EMP_NO;

SELECT 
	EMP_NO ,
    MAX(FROM_DATE) AS FROM_DATE ,
    MAX(TO_DATE) AS TO_DATE
FROM dept_emp
GROUP BY EMP_NO;