/*
EXTRACT A LLIST OF ALL NAMES THAT ARE ENCOUNTERED LESS THAN 200 TIMES LET THE DATA REFER TO PEOPLE HIRED AFTER THE 1ST OF JANUARY 1999.
*/
SELECT FIRST_NAME , LAST_NAME , COUNT(FIRST_NAME) AS NAMES_COUNT
FROM employees
WHERE HIRE_DATE > '1999-01-01'
GROUP BY FIRST_NAME
HAVING COUNT(FIRST_NAME) < 200
ORDER BY FIRST_NAME;